apiVersion: apps/v1
kind: Deployment
metadata:
  name:  client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - image:  ujjwal25/multi-client
          name:  client
          ports:
            - containerPort: 3000 
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          
